# Generated by Django 4.1 on 2022-09-01 22:36

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=300, unique=True, verbose_name='email address')),
                ('company', models.CharField(max_length=50, verbose_name='company name')),
                ('joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='account created')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('userType', models.CharField(max_length=30, verbose_name='user type')),
                ('phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(regex='^([0-9]{9,11})$')], verbose_name='phone number')),
                ('jobPosition', models.CharField(max_length=50, verbose_name='job position')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
