# Generated by Django 4.1 on 2022-09-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(max_length=50, null=True, verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='jobPosition',
            field=models.CharField(max_length=50, null=True, verbose_name='job position'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='name'),
        ),
    ]
