# Generated by Django 4.1 on 2022-09-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached', models.FileField(blank=True, upload_to='', verbose_name='첨부 파일')),
            ],
        ),
    ]
