# Generated by Django 4.1 on 2022-09-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boltnnut', '0003_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
