# Generated by Django 4.1 on 2022-09-07 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boltnnut', '0005_rename_expired_negotiation_project_expired_negotiate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='attached',
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='Uploaded Files/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boltnnut.project')),
            ],
        ),
    ]
