# Generated by Django 4.1 on 2022-09-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boltnnut', '0006_remove_project_attached_projectfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ongoing',
            field=models.BooleanField(default=True),
        ),
    ]
