# Generated by Django 4.1 on 2022-09-22 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boltnnut', '0008_rename_partners_partner_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectfile', to='boltnnut.project'),
        ),
    ]
