# Generated by Django 4.1 on 2022-09-23 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boltnnut', '0009_alter_projectfile_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='profile',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boltnnut.project'),
        ),
    ]
